name: Validate HTML with Proof HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        working-directory: frontend
        run: npm run build

      - name: Validate HTML
        uses: anishathalye/proof-html@v2.0.3
        with:
          directory: "build"
